# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hw1.xdc

# Block Designs: bd/hw1_BD/hw1_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD || ORIG_REF_NAME==hw1_BD} -quiet] -quiet

# IP: bd/hw1_BD/ip/hw1_BD_my_led_ip_0_0/hw1_BD_my_led_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD_my_led_ip_0_0 || ORIG_REF_NAME==hw1_BD_my_led_ip_0_0} -quiet] -quiet

# IP: bd/hw1_BD/ip/hw1_BD_processing_system7_0_1/hw1_BD_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD_processing_system7_0_1 || ORIG_REF_NAME==hw1_BD_processing_system7_0_1} -quiet] -quiet

# IP: bd/hw1_BD/ip/hw1_BD_axi_gpio_0_1/hw1_BD_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD_axi_gpio_0_1 || ORIG_REF_NAME==hw1_BD_axi_gpio_0_1} -quiet] -quiet

# IP: bd/hw1_BD/ip/hw1_BD_proc_sys_reset_0_1/hw1_BD_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD_proc_sys_reset_0_1 || ORIG_REF_NAME==hw1_BD_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/hw1_BD/ip/hw1_BD_ps7_0_axi_periph_3/hw1_BD_ps7_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD_ps7_0_axi_periph_3 || ORIG_REF_NAME==hw1_BD_ps7_0_axi_periph_3} -quiet] -quiet

# IP: bd/hw1_BD/ip/hw1_BD_auto_pc_0/hw1_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw1_BD_auto_pc_0 || ORIG_REF_NAME==hw1_BD_auto_pc_0} -quiet] -quiet

# XDC: bd/hw1_BD/hw1_BD_ooc.xdc
