# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/Vivado_data/hw_1/hw_1.srcs/sources_1/bd/block_design/ip/block_design_processing_system7_0_1/block_design_processing_system7_0_1.xci
# IP: The module: 'block_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Vivado_data/hw_1/hw_1.srcs/sources_1/bd/block_design/ip/block_design_processing_system7_0_1/block_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Documents/Vivado_data/hw_1/hw_1.srcs/sources_1/bd/block_design/ip/block_design_processing_system7_0_1/block_design_processing_system7_0_1.xci
# IP: The module: 'block_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Vivado_data/hw_1/hw_1.srcs/sources_1/bd/block_design/ip/block_design_processing_system7_0_1/block_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
